#!/bin/bash
# SSL initialization script (runs during initdb phase as fallback)
# Primary SSL generation happens in wrapper.sh

CERTS_DIR="/var/lib/postgresql/data/certs"

# Skip if certs already exist (generated by wrapper.sh)
if [ -f "$CERTS_DIR/server.crt" ] && [ -f "$CERTS_DIR/server.key" ]; then
    echo "SSL certificates already exist, skipping init-ssl.sh"
    exit 0
fi

echo "Generating SSL certificates in init-ssl.sh (fallback)..."

DAYS="${SSL_CERT_DAYS:-820}"

sudo mkdir -p "$CERTS_DIR"
sudo chown postgres:postgres "$CERTS_DIR"

# Generate CA
openssl genrsa -out "$CERTS_DIR/ca.key" 2048
openssl req -new -x509 -days "$DAYS" -key "$CERTS_DIR/ca.key" -out "$CERTS_DIR/ca.crt" \
    -subj "/CN=PostgreSQL CA"

# Generate server cert
openssl genrsa -out "$CERTS_DIR/server.key" 2048
openssl req -new -key "$CERTS_DIR/server.key" -out "$CERTS_DIR/server.csr" \
    -subj "/CN=postgres"

cat > "$CERTS_DIR/v3.ext" <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = DNS:localhost,DNS:*.railway.internal,IP:127.0.0.1
EOF

openssl x509 -req -in "$CERTS_DIR/server.csr" -CA "$CERTS_DIR/ca.crt" -CAkey "$CERTS_DIR/ca.key" \
    -CAcreateserial -out "$CERTS_DIR/server.crt" -days "$DAYS" -extfile "$CERTS_DIR/v3.ext"

chmod 600 "$CERTS_DIR/server.key"
chmod 644 "$CERTS_DIR/server.crt" "$CERTS_DIR/ca.crt"

echo "SSL certificates generated"
